# Generated by Django 3.0.3 on 2020-02-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_worldborder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldborder',
            name='fips',
            field=models.CharField(max_length=2, null=True, verbose_name='FIPS Code'),
        ),
    ]
